### ISSUE TITLE
styleModifier and message tag conflicting

### ISSUE THREAD

**Issue by theorise** [pattern-lab/patternlab-node#184] opened 2015-11-13 13:48 UTC
I am having troubles combining both `{{styleModifier}}` and `{{message}}` when calling the same pattern multiple times. It seems to just find the first `{{styleModifier}}` and repeat it _only_ when `{{message}}` is also being used.

---

Atom:
```
<span class="test-class_base {{styleModifier}}">
	[test][{{message}}]
</span>
```

---

`{{styleModifier}}` works when I call the following:
```
<div class="test-group">
	{{> atoms-test:testclass1 }}
	{{> atoms-test:testclass2 }}
	{{> atoms-test:testclass3 }}
	{{> atoms-test:testclass4 }}
</div>
```

Output:
```
<div class="test-group">
    <span class="test-class_base testclass1">
        [test][]
    </span>
    <span class="test-class_base testclass2">
        [test][]
    </span>

    <span class="test-class_base testclass3">
        [test][]
    </span>

    <span class="test-class_base testclass4">
        [test][]
    </span>
</div>
```

---

`{{message}}` works when I call the following:
```
<div class="test-group">
	{{> atoms-test(message: "{{test.one}}" ) }}
	{{> atoms-test(message: "{{test.two}}" ) }}
	{{> atoms-test(message: "{{test.three}}" ) }}
	{{> atoms-test(message: "test-4" ) }}
</div>
```

Output:
```
<div class="test-group">
	<span class="test-class_base ">
		[test][test-1]
	</span>

	<span class="test-class_base ">
		[test][test-2]
	</span>

	<span class="test-class_base ">
		[test][test-3]
	</span>

	<span class="test-class_base ">
		[test][test-4]
	</span>
</div>
```

---

`{{message}}` works but `{{styleModifier}}` **does not** (it repeats the first instance) when I call the following:
```
<div class="test-group">
	{{> atoms-test:testclass1(message: "{{test.one}}" ) }}
	{{> atoms-test:testclass2(message: "{{test.two}}" ) }}
	{{> atoms-test:testclass3(message: "{{test.three}}" ) }}
	{{> atoms-test:testclass4(message: "test-4" ) }}
</div>
```

Output:
```
<div class="test-group">
	<span class="test-class_base testclass1">
		[test][test-1]
	</span>

	<span class="test-class_base testclass1">
		[test][test-2]
	</span>

	<span class="test-class_base testclass1">
		[test][test-3]
	</span>

	<span class="test-class_base testclass1">
		[test][test-4]
	</span>
</div>
```

**Comment by bmuenzenmeyer** [comment] 2015-11-13 14:21
Thanks for the thorough test cases. A quick glance makes me think some of this syntax was not considered or supported. Do you know if all of this works in PL PHP? I try to emulate that wherever possible but would be lying if I said I had parity in every feature yet.

**Comment by theorise** [comment] 2015-11-13 14:37
I am unsure if this is working with PHP PL, I did a brief search and I found no similar issues.

**Comment by bmuenzenmeyer** [comment] 2015-11-13 14:42
No problem. I'll try to look into all of this soon-ish.... probably next
week.

**Comment by bmuenzenmeyer** [comment] 2015-11-25 06:49
Using the similar test harness of https://github.com/pattern-lab/patternlab-node/issues/190 I get this:

![image](https://cloud.githubusercontent.com/assets/298435/11390245/cf9bd2a8-930d-11e5-85bf-ffe41dbce161.png)

even putting in the partials as values like so:
```
{{> atoms-avatar:foo1(message: "{{name.first}}") }}
{{> atoms-avatar:foo2(message: "{{name.middle}}") }}
{{> atoms-avatar:foo3(message: "{{name.last}}") }}
{{> atoms-avatar:foo4(message: "4") }}
```

yields:

![image](https://cloud.githubusercontent.com/assets/298435/11390277/354349ec-930e-11e5-96dc-9b170552092c.png)

Therefore, this is a duplicate of #190 and should be resolved with same fix near as I can tell.

**Comment by bmuenzenmeyer** [comment] 2015-11-25 07:06
@theorise please upgrade to v0.15.1 and try your test cases again!

**Closed by bmuenzenmeyer** 2015-11-25 07:06 UTC
Labels: bug, duplicate, staged for next release
