### ISSUE TITLE
Using Yarn to install dependencies on Mac results in file encoding issues (CRLF)

### ISSUE THREAD

**Issue by Seanom** [pattern-lab/patternlab-node#967] opened 2018-10-31 09:41 UTC
I am using Pattern Lab Node `v3.0.0.0-beta.1` on `Mac High Sirerra`, with Node `v10.11.0`, using a `Vanilla` Edition.

There is an issue when using Yarn on unix based systems, I'm using a Mac but I've seen people using Ubuntu experience the same problem and I've not seen it jotted down yet here.

When running 'yarn' files are installed using the encoded line breaks, it appears that NPM changes this to the system specific version. However if the file is encoded with CRLF then this results in the following message

```
env: node\r: No such file or directory
```

This does not occur on windows, and only appears if you install using `yarn` to get around this it's possible to install using `npm install` and then using `yarn` to run scripts

There is an issue about this over on the yarn github page https://github.com/yarnpkg/yarn/issues/5480
I've also spotted a couple of people in the pattern lab gitter.im channel.

##### Expected Behavior
Files are encoded using LF line separators

##### Actual Behavior
Many of the files are encoded using CRLF line separators, which results in the error when using `yarn`

```
env: node\r: No such file or directory
```

##### Steps to Reproduce
Reproduced on a mac High Sierra 10.13.6

- Ensure the package.json exists (I used the following)
    ```
     {
      "name": "test",
      "version": "1.0.0",
      "description": "",
      "main": "index.js",
      "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1",
        "pl:build": "patternlab build --config ./patternlab-config.json",
        "pl:help": "patternlab --help",
        "pl:install": "patternlab install --config ./patternlab-config.json",
        "pl:serve": "patternlab serve --config ./patternlab-config.json",
        "pl:version": "patternlab --version"
      },
      "keywords": [],
      "author": "",
      "license": "ISC",
      "dependencies": {
        "@pattern-lab/cli": "^0.0.1-beta.1",
        "@pattern-lab/core": "^3.0.0-beta.1",
        "@pattern-lab/engine-mustache": "^2.0.0-beta.0",
        "@pattern-lab/uikit-workshop": "^1.0.0-beta.0"
      }
     }
     ```
- Run `yarn` (everything installs)
- Run `yarn pl:help`
- Observe the error message 
    ```
    yarn run v1.10.1
    $ patternlab --help
    env: node\r: No such file or directory
    error Command failed with exit code 127.
   ```

It's also possible to run the following
 - `npm init -y && npx @pattern-lab/cli -c patternlab init`
 - Leave the directory as default
 - Install node version
 - Select `None` for the starter template
 - Once installed delete the node_modules folder
 - Run `yarn`
 - Run `yarn pl:help`
 - Observe, the error message as above

**Comment by DanielRuf** [comment] 2018-11-02 10:35
Same here, using latest version of Yarn and Node 10 LTS.

**Comment by DanielRuf** [comment] 2019-01-19 08:45
I hate sucb bots like the stale bot.

**Comment by DanielRuf** [comment] 2019-01-19 08:45
I hate such bots like the stale bot.

**Comment by jp-sauve** [comment] 2019-02-09 00:42
This is still relevant.
```
{
  "name": "patternlab",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "patternlab": "patternlab",
    "pl:build": "patternlab build --config ./patternlab-config.json",
    "pl:help": "patternlab --help",
    "pl:install": "patternlab install --config ./patternlab-config.json",
    "pl:serve": "patternlab serve --config ./patternlab-config.json",
    "pl:version": "patternlab --version"
  },
  "devDependencies": {
    "@pattern-lab/cli": "^0.0.1-beta.1"
  },
  "dependencies": {
    "@pattern-lab/cli": "^0.0.1-beta.1",
    "@pattern-lab/core": "^3.0.0-beta.1",
    "@pattern-lab/engine-mustache": "^2.0.0-beta.0",
    "@pattern-lab/uikit-workshop": "^1.0.0-beta.0",
    "starterkit-twig-drupal-demo": "pattern-lab/starterkit-twig-drupal-demo"
  }
}
```
and here's some log output for you. I'm using Linux.
```
1 verbose cli [ '/home/fathead/.nvm/versions/node/v10.5.0/bin/node',
1 verbose cli   '/home/fathead/.nvm/versions/node/v10.5.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'patternlab',
1 verbose cli   '--',
1 verbose cli   'serve' ]
2 info using npm@6.1.0
3 info using node@v10.5.0
4 verbose run-script [ 'prepatternlab', 'patternlab', 'postpatternlab' ]
5 info lifecycle patternlab@1.0.0~prepatternlab: patternlab@1.0.0
6 info lifecycle patternlab@1.0.0~patternlab: patternlab@1.0.0
7 verbose lifecycle patternlab@1.0.0~patternlab: unsafe-perm in lifecycle true
8 verbose lifecycle patternlab@1.0.0~patternlab: PATH: /home/fathead/.nvm/versions/node/v10.5.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/fathead/Workspace/patternlab/node_modules/.bin:/home/fathead/.yarn/bin:/home/fathead/.config/yarn/global/node_modules/.bin:/home/fathead/.nvm/versions/node/v10.5.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/home/fathead/bin:/home/fathead/.npm-packages/bin
9 verbose lifecycle patternlab@1.0.0~patternlab: CWD: /home/fathead/Workspace/patternlab
10 silly lifecycle patternlab@1.0.0~patternlab: Args: [ '-c', 'patternlab "serve"' ]
11 info lifecycle patternlab@1.0.0~patternlab: Failed to exec patternlab script
12 verbose stack Error: patternlab@1.0.0 patternlab: `patternlab "serve"`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/home/fathead/.nvm/versions/node/v10.5.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:182:13)
12 verbose stack     at maybeClose (internal/child_process.js:961:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
13 verbose pkgid patternlab@1.0.0
14 verbose cwd /home/fathead/Workspace/patternlab
15 verbose Linux 4.15.0-45-generic
16 verbose argv "/home/fathead/.nvm/versions/node/v10.5.0/bin/node" "/home/fathead/.nvm/versions/node/v10.5.0/bin/npm" "run" "patternlab" "--" "serve"
17 verbose node v10.5.0
18 verbose npm  v6.1.0
19 error file sh
20 error code ELIFECYCLE
21 error errno ENOENT
22 error syscall spawn
23 error patternlab@1.0.0 patternlab: `patternlab "serve"`
```

**Comment by DanielRuf** [comment] 2019-02-09 05:57
> This is still relevant.

Sure, this is why it was reopened ;-)

**Comment by zachariab** [comment] 2019-03-27 00:58
Upgrading @pattern-lab/cli to **0.0.1-beta.2** resolved this issue for me. I'm not quite sure why, though.

I verified there are CRLF line separators in the file [packages/cli/bin/patternlab.js](https://github.com/pattern-lab/patternlab-node/blob/dev/packages/cli/bin/patternlab.js) at 0.0.1-beta.1 that are fixed in 0.0.1-beta.2. That's true using either yarn or npm, although npm changes the first line break to at LF preventing the "No such file or directory" error. 

The mystery is I couldn't find a commit that would change the line ending in that file between beta.1 and beta.2. In any case, it's working for me now.

**Comment by zachariab** [comment] 2019-03-29 04:02
My best guess is that this is related to the npm issue [npm publish from Windows handles CRLF incorrectly](https://github.com/npm/npm/issues/2097)

Is it possible that the releases prior to 0.0.1-beta.2 were published from a windows machine but newer ones from mac/unix? That would explain the CRLF I'm seeing in previous releases, which npm fixes but yarn does not.

**Comment by DanielRuf** [comment] 2019-05-28 04:17
Not stale, still relevant.

**Comment by DanielRuf** [comment] 2019-07-27 08:56
Bump.

**Comment by DanielRuf** [comment] 2019-09-25 11:04
Not stale.

**Comment by bradjones1** [comment] 2021-04-19 23:52
Not stale.

**Comment by roman-sitewits** [comment] 2021-05-17 01:04
Still relevant!!!

Also here is the yarn bug:
[https://github.com/yarnpkg/yarn/issues/5480](https://github.com/yarnpkg/yarn/issues/5480)

**Comment by theLine** [comment] 2021-09-21 07:11
I'm getting the same error on MacOS 11.6.
It seems that it doesn't matter whether I use yarn (1.22.11) or npm (6.14.13) with node v14. 
The executable (`node_modules/.bin/patternlab`) still will get windows line-endings.

EDIT: I found a workaround. I've installed `dos2unix-cli` and added a `postinstall` hook in the `package.json`:
```
  "scripts": {
    "postinstall": "dos2unix node_modules/.bin/patternlab"
  },
```

**Comment by mfranzke** [comment] 2022-01-30 12:00
@Seanom it looks like that we finally solved this problem with https://github.com/pattern-lab/patternlab-node/pull/1397/, I cannot reproduce the problem any more with the newest pattern lab version 5.16.1

**Comment by wesleyboar** [comment] 2022-02-03 18:46
I also cannot reproduce the issue since v5.16.1. (I could reproduce it with an earlier version—I forgot which.)

<details>
<summary>Details</summary>

I am using Pattern Lab Node `v5.16.1` on `Mac Monterey`, with Node `v17.4.0`, using a `Vanilla` Edition.

</details>

**Closed** 2022-02-03 23:19 UTC
Labels: help wanted :sos:, good first issue :mortar_board:
