### ISSUE TITLE
styleModifiers are not included in pseudo patterns

### ISSUE THREAD

**Issue by gael-boyenval** [pattern-lab/patternlab-node#474] opened 2016-09-19 13:06 UTC
I am using Pattern Lab Node `v2.5.0` on `Mac`, with Node `v6+`, using the `Gulp` Edition.

##### Expected Behavior
for a given pattern X and his pseudo pattern :

patternX:
```
<h2>{{ data }}</h2>
{{> patternY:modifier--foo }}
```

patternX~pseudo.json:
```
{ data: "yyy" }
```

this should output  the included pattern Y with the style modifier
patternX-pseudo html output : 
```
<h2> yyy </h2>
<div class="patternY modifier--foo">
       bar
</div>
```

##### Actual Behavior
The styleModifier is not included :
```
<h2> yyy </h2>
<div class="patternY">
       bar
</div>
```

**Comment by bmuenzenmeyer** [comment] 2016-09-22 12:59
@gael-boyenval in your above breakdown, patternY.mustache looks like this correct?

```
<div class="patternY {{styleModifier}}">
  bar
</div>
```

**Comment by bmuenzenmeyer** [comment] 2016-09-22 13:03
confirmed bug.

![image](https://cloud.githubusercontent.com/assets/298435/18749134/10b057ca-809b-11e6-84c8-e5c6edb1c8b8.png)

**Comment by bmuenzenmeyer** [comment] 2016-09-22 13:04
[pseudomodifier474.zip](https://github.com/pattern-lab/patternlab-node/files/487312/pseudomodifier474.zip)

test files

**Comment by gael-boyenval** [comment] 2016-09-22 13:08
@bmuenzenmeyer : yes exactly !

**Comment by bmuenzenmeyer** [comment] 2016-09-22 17:00
@gael-boyenval this will be fixed with the next version release. !

**Closed** 2016-09-27 13:26 UTC
Labels: bug, staged for next release
