### ISSUE TITLE
Saving _data or _meta files breaks server/watcher

### ISSUE THREAD

**Issue by danwhite85** [pattern-lab/patternlab-node#763] opened 2017-12-08 17:43 UTC
version: v3.0.0-alpha.5

When running patternlab.serve. If a file in _data or _meta are changed rimraf throws the following error and crashes the server/watcher.

`Error: ENOTEMPTY: directory not empty, rmdir 'C:\web-projects\patternlab-node-3.0-demo-vanilla-master\patternlab-node-3.0-demo-vanilla-master\public\patterns'`

The call stack shows the issue being in the cleanBuildDirectory method at https://github.com/pattern-lab/patternlab-node/blob/master/core/lib/patternlab.js#L619

**Comment by raphaelokon** [comment] 2018-01-18 09:39
I can look into this one @bmuenzenmeyer

**Comment by raphaelokon** [comment] 2018-01-21 11:31
I debugged this one using https://github.com/pattern-lab/edition-node-gulp/releases/tag/v2.0.0-alpha.1 /w core v3.0.0-alpha.6 but couldn't reproduce this issue but found another one (`chmod` error resulting in unhandled promise). @danwhite85 Could you share a minimal config including this bug? This would be a massive help. Thanks

**Comment by bmuenzenmeyer** [comment] 2018-01-22 20:26
This should now be fixed on `dev`

**Closed** 2018-02-22 15:17 UTC
Labels: bug:v3 :bug:, pinned, staged for next release
