### ISSUE TITLE
Pattern parameters with `()` as a value are not rendered correctly

### ISSUE THREAD

**Issue by ajilderda** [pattern-lab/patternlab-node#673] opened 2017-07-31 20:44 UTC
I am using Pattern Lab Node `v2.9.3` on `Mac`, with Node `v6.11.1`, using the `Gulp` Edition.

##### Expected Behavior
Pattern parameters with `()` as a value should render correctly.
`{{> molecules-pattern( title: "this is causing the issue: ()") }}`
The example above should render the pattern molecule with `this is causing the issue: ()` as its data input.

##### Actual Behavior
When `()` is added to a pattern parameter the pattern silently fails and no data is coming through to the pattern.

##### Steps to Reproduce
1. Create an atom named `pattern` with a field `{{ title }}`
2. Reference the pattern with a pattern parameter including `()`: ` {{> atoms-pattern(title: "I should render ()")`
3. The pattern parameter is ignored.
4. Remove the `()` from the parameter : `{{> atoms-pattern(title: "I should render")`
5. The pattern renders and the `title` displays properly

Reference: https://github.com/pattern-lab/patternlab-node/issues/473#issuecomment-318584549

**Comment by jdagerot** [comment] 2017-08-17 14:59
I can confirm this "I should render (" works great, but "I should render )" doesn't not. Looks like it's the closing ) that generates a problem.

**Comment by ajilderda** [comment] 2017-10-16 16:07
Not so quick @stale[bot] 🖐

**Comment by bmuenzenmeyer** [comment] 2017-10-16 16:13
@ajilderda thanks for the poke. I've pinned this to no longer close due to inactivity.

**Comment by mwinkelm** [comment] 2017-11-14 09:58
I have the same problem with v2.12.0. For now it's OK to go without parentheses, but a fix would be great,

**Comment by bmuenzenmeyer** [comment] 2017-11-15 14:45
PRs welcome!

**Comment by jdagerot** [comment] 2017-11-15 15:04
Ok, I made a fast example over here: https://github.com/jdagerot/edition-node-gulp.git

**Comment by mfranzke** [comment] 2020-06-20 01:44
I am using Pattern Lab Node `v5.10.1` on Mac OS, with Node `v13.12.0`, using `@pattern-lab/edition-node` Edition. As `handlebars` is the successor of `mustache` as the template language, I've used the `.hbs` and the following template:
``` hbs
{{> atoms-pattern title="I should render ()" }}
```

and even also 

``` hbs
{{> atoms-pattern title="I should render =" }}
```

The problem doesn’t occur any more on this setup. Could you please retest ?

**Closed** 2020-08-16 17:10 UTC
Labels: pinned 📌
