### ISSUE TITLE
Annoying warning with Pattern-specific Data

### ISSUE THREAD

**Issue by danwhite85** [pattern-lab/patternlab-node#808] opened 2018-02-27 23:31 UTC
An annoying warning is being logged for all pattern-specific json data.
![image](https://user-images.githubusercontent.com/636470/36761285-30de956e-1bd3-11e8-91b7-af56f1170e79.png)

Maybe there should be a check in the following file:
https://github.com/pattern-lab/patternlab-node/blob/master/core/lib/get.js#L36

**Comment by bmuenzenmeyer** [comment] 2018-02-28 00:39
hey @danwhite85 thanks for the report. I cannot thank you enough for testing out the new version of Pattern Lab.

I think this is a duplicate of https://github.com/pattern-lab/patternlab-node/issues/786 and therefore I am closing it. I'll make sure json is included in the above fix..

🥂

**Closed by bmuenzenmeyer** 2018-02-28 00:39 UTC
