### ISSUE TITLE
View All link missing from main Pattern Lab navigation bar

### ISSUE THREAD

**Issue by coreylafferty** [pattern-lab/patternlab-node#1048] opened 2019-09-03 17:43 UTC
I am using Pattern Lab Node `v3.0.3` on `Windows`, with Node `v10.15.1`, using the `Twig` Edition.

##### Expected Behavior
A 'view all' link or something similar (e.g., clicking the Pattern Lab logo) takes you back to the main Pattern Lab page that lists all components.

##### Actual Behavior
No 'view all' link present.  

![image](https://user-images.githubusercontent.com/1557952/64195977-c89dc880-ce50-11e9-8348-6d52eb2e5b7a.png)

**Comment by sghoweri** [comment] 2019-09-03 22:55
Assigning this to me — this should be a straightforward UIKit fix to roll out since the code re-enabling this top level All link was just commented out 🤦‍♂

**Comment by bmuenzenmeyer** [comment] 2019-09-04 03:29
adding this featue way back in PL PHP was my very first contribution to PL ❤️

**Closed** 2019-09-14 13:08 UTC

**Comment by thethomic** [comment] 2019-09-16 06:38
Is it by design, that the "View All" Link inside the several folders is still showing up?
I expected this link to dissappear too when `ishControlsHide.views-all: true,`
