### ISSUE TITLE
Edits to twig files included in parent do not appear until the parent file is updated

### ISSUE THREAD

**Issue by a-fro** [pattern-lab/patternlab-node#1015] opened 2019-05-17 13:37 UTC
I am using Pattern Lab Node `v3.0.0` on `Mac`, with Node `v8.14.0`, using the `Twig` Edition.

##### Expected Behavior
After running `npm create pattern-lab` and choosing the `starterkit-twig-demo`, I expect that while viewing a browser pages such as the comment thread in patternlab, I will see the page reload when I make changes to the included twig file (e.g. editing the `02-single-comment.twig` file). 

##### Actual Behavior
In order to see the changes, I have to edit `00-comment-thread.twig`, which then shows changes to both the parent template and it's included child templates. 

##### Steps to Reproduce

1. clone and install pl
2. Choose the twig edition and twig starterkit demo.
3. Visit an organism in the browser, such as the comment thread.
4. Make an edit to the `02-single-comment.twig` file, which the comment thread includes.
5. Notice that PL reloads, but changes do not appear.
6. Edit `00-comment-thread.twig`, and then both changes appear.

**Comment by nietzscheson** [comment] 2019-05-21 22:34
I confirm this issue... It happens me exactly the same. I had to use node+mustache. Is very sad! 😞

**Comment by sghoweri** [comment] 2019-05-22 18:34
CC @EvanLovely 🤔

**Comment by EvanLovely** [comment] 2019-05-22 23:43
I feel like this has to do with the incremental rebuilds

**Comment by a-fro** [comment] 2019-07-22 13:28
I'm happy to do some debugging if anyone can point me in the right direction.

**Comment by zhawkins** [comment] 2019-08-06 22:04
This looks like it could be worked around if the `cleanPublic` config worked as expected. Meaning it would do a full rebuild if you changed a file vs an incremental build. 

Looks like there are a couple of issues surrounding this issue. 
988 which has a PR: https://github.com/pattern-lab/patternlab-node/pull/989

1024 is also related to `cleanPublic` not working.

**Comment by zhawkins** [comment] 2019-08-06 22:27
As a follow up I used https://www.npmjs.com/package/patch-package to patch CLI and I can no longer reproduce the issue with `cleanPublic` set to `true`. 

This doesn't solve the incremental build issue with nested templates but it helps me avoid the issue in the meantime. ¯\_(ツ)_/¯

**Comment by zhawkins** [comment] 2019-08-20 18:42
@a-fro I've got a PR up that resolves this issue if you want to check it out https://github.com/pattern-lab/patternlab-node/pull/1036.

It's possible there's a better way to do this but it does work following your original testing instructions. I've also tested it on a project of ours where we were having the same issue.

**Comment by sghoweri** [comment] 2019-10-14 10:51
FYI, I merged in the fix for this yesterday + this was published to NPM ~6 hours ago!

**Closed by sghoweri** 2019-10-14 10:51 UTC

**Comment by zhawkins** [comment] 2019-10-14 13:55
Thanks Salem!
