### ISSUE TITLE
Nothing compiling to patterns folder

### ISSUE THREAD

**Issue by chazchumley** [pattern-lab/patternlab-node#1479] opened 2023-02-01 13:32 UTC
I am using Pattern Lab Node 6 on Mac with Node  v16.16.0 using a Vanilla Edition.

I am using the Twig engine with the demo and when running `npm run start` I would expect to see Pattern Lab rendering any atoms, molecules, etc.

Instead, I have an empty Pattern Lab instance and nothing is being output in the public/patterns folder.

Steps to reproduce:
1) npm create pattern-lab

Follow the prompts for a Twig version.

**Comment by JosefBredereck** [comment] 2023-02-01 20:21
Closing duplicate of #1477

**Closed as completed by JosefBredereck** 2023-02-01 20:21 UTC
