### ISSUE TITLE
Viewall Patten breaks if a folder includes a markdown file

### ISSUE THREAD

**Issue by Seanom** [pattern-lab/patternlab-node#970] opened 2018-11-14 16:07 UTC
I am using Pattern Lab Node `v3.0.0-beta.1` on `Mac`, with Node `v10.11.0`, using a `Vanilla` Edition.

When a markdown file is added to the directories parent folder the View All link for that section breaks resulting the following error message in the console.
`Uncaught TypeError: Cannot read property 'innerHTML' of null` traced back to the following line `patternlab-viewer.js:formatted:6047`

Using the md file at the folder level appears to be the issue, removing or changing the name(so it does not match a directory) appears to resolve the issue but removes the text from the md file.

Visiting the link directly displays the page without the error message.

Selecting the View All for all of the patterns also appears to work this is limited to the folder that also has an associated md file.

The issue looks to be caused by the partial having trouble getting the div with ID `pl-pattern-data-footer` from the JS 

```
document.getElementById("pl-pattern-data-footer").innerHTML,
```

##### Expected Behavior
Adding a md file to a folder displays additional information above the mustache content.

##### Actual Behavior
Adding a md file at the folder level causes an issue within the JS that results in Pattern lab repeating the navigation bar and displaying the Loading Pattern Lab message, until the page is refreshed.
![image](https://user-images.githubusercontent.com/331839/48494769-72f72180-e826-11e8-89e0-c1c2526f8d46.png)

##### Steps to Reproduce
1. Install the node version of PL
2. Install the basic mustache starter kit
3. Within the 00-atoms folder ensure that there is a 00-global directory
4. Within the 00-atoms folder ensure there is a global.md file
5. Build the PL and visit the local site
6. From the dropdown go to Atoms > Global > Viewall
7. Observe that the error message is displayed
    
    ![image](https://user-images.githubusercontent.com/331839/48494645-39beb180-e826-11e8-8ed3-854e030a60e3.png)

8. Enter the URL into the browser `http://127.0.0.1:3000/?p=viewall-atoms-global`
9. Observe that the page displays correctly 
10. Press the link on the page `Global`
11. Observe the page reloads and displays the broken page again
      This time the error message is slightly different 
      ![image](https://user-images.githubusercontent.com/331839/48494568-13991180-e826-11e8-9800-b9be5081f738.png)

12. Remove or rename the global.md within the 00-atoms directory and rebuild PL
13. From the dropdown go to Atoms > Global > Viewall
14. Observe the page now loads correctly

**Comment by Seanom** [comment] 2018-11-14 16:08
I did try changing the folder to remove the 00- from both atoms and the global folder and also adding 00- to the global.md file, but still experienced the same issue.

**Comment by bmuenzenmeyer** [comment] 2018-11-14 16:41
This is a duplicate of #452 https://github.com/pattern-lab/patternlab-node/issues/890, and matches the debugging I have done so far on the issue.

**Comment by Seanom** [comment] 2018-11-15 08:46
Ahh sorry, I did some searching first for duplicates, but done so in the wrong repo

**Comment by bmuenzenmeyer** [comment] 2019-06-25 20:56
@sghoweri is this still an issue we need fixing?

**Comment by sghoweri** [comment] 2019-06-25 21:38
@bmuenzenmeyer yep, I definitely think this is still an issue with the latest PL Node release.

Did you ever get a chance to check out my (potential) fix for this in https://github.com/pattern-lab/patternlab-node/pull/977?

**Comment by bmuenzenmeyer** [comment] 2019-06-27 03:06
If memory serves... we discovered it needed more than that. Lemme look
again soon-ish

**Closed** 2019-09-25 03:33 UTC
Labels: needs response 🤙
