### ISSUE TITLE
Patterns with Pattern Parameters Cannot Be Overwritten Downstream

### ISSUE THREAD

**Issue by e2tha-e** [pattern-lab/patternlab-node#250] opened 2016-02-17 11:30 UTC
To replicate:
- Edit `source/_patterns/04-pages/00-homepage.mustache`
- Replace the content with this mustache code: `{{> templates-homepage(emergency: true) }}`
- This will render correctly in the Pattern Lab UI.
- Edit `source/_patterns/03-templates/00-homepage.mustache`
- Replace `{{> molecules-alert }}` with `{{> molecules-alert(alertClass: 'error') }}`
- This causes the emergency block to disappear instead of appearing with the correct alert class.

**Comment by bmuenzenmeyer** [comment] 2016-02-17 13:26
To my knowledge, this is the expected behavior since pattern parameters were released - since encountering a pattern parameter causes immediate consumption of the data effectively closing off downstream changes. 

Does having a file like `.source/_patterns/04-pages/00-homepage~emergency.json` work for you?

**Comment by e2tha-e** [comment] 2016-02-17 23:37
I remember doing recursive parameter submission all the time in Pattern Lab PHP, but wanted to be absolutely sure the latest version does it, and v1.0.0 definitely does it. Making the the exact code changes as in my first comment gets the alert class to show correctly.

Tilde-appended variants aren't the best option if you want to view components up and down the stream because you'll repeat definitions in multiple .json files, which goes against the DRY principle.

In any case, the emergency block shouldn't just disappear because of a downstream parameter submission.

**Comment by bmuenzenmeyer** [comment] 2016-02-18 02:01
Hey @e2tha-e thanks for checking. I think I have a proposed solution that I might hack out and try as a branch. Welcome to suggestions for anyone too

**Comment by theorise** [comment] 2016-02-18 09:06
I just wanted to say I came across this just yesterday and it is certainly something that would be great to have. 

I may be abusing pattern parameters, but I am passing things such as data-attributes as JS hooks for components. In my use case: 

We have a reusable icon atom, inside a reusable off-canvas organism. The icon acts as the close button:

`{{> atoms-icon:icon--cross(iconDataAttributes:'data-off-canvas-toggle="toggle-target"') }`

The molecule is included in certain templates, but it needs to be included as the following:

`{{> organisms-off-canvas:off-canvas_small|off-canvas_right(offCanvasSelector:'toggle-target') }}`

**Comment by bmuenzenmeyer** [comment] 2016-02-18 13:42
Morning

The specifics of this issue seemed acceptable to me for a long time since only people using the more advanced features under certain scenarios would encounter this problem, and really one is left with many options as workarounds.

So I appreciate the additional information and :+1:  - it's very valuable to me to see how people are using PL Node.

**Comment by e2tha-e** [comment] 2016-02-18 16:02
@theorise That's exactly the sort of use-case which is not abuse, and would avoid the maintenance headache of making sure everything's up-to-date and correctly spelled in multiple places.

**Comment by bmuenzenmeyer** [comment] 2016-02-24 06:30
Hey all - I pushed to the `250` branch a small tweak that I think fixes this - at least for the example  that @e2tha-e originally reported. Could you all clang on it and see if it works?

Todo:

- [ ] confirm fix
- [ ] revert mustache changes
- [ ] add a unit test covering this scenario

**Comment by vebersol** [comment] 2016-02-24 17:22
Hi @bmuenzenmeyer,

I've been testing this branch in a running project our team is working on - based on PHP version. We're trying to migrate to node version, nevertheless this bug was a real problem and we're trying to help you to find a solution and I see this solution that came first is currently working in our real case.

So, I can confirm it's working in many different levels.

**Comment by bmuenzenmeyer** [comment] 2016-02-24 17:29
@vebersol  That is very good to hear as a first report of success. Thanks for letting me know! I am working on some unit test coverage right now too.

**Comment by bmuenzenmeyer** [comment] 2016-02-25 13:11
@e2tha-e could you please make sure this branch addresses your original issue?

**Comment by e2tha-e** [comment] 2016-02-25 19:52
@bmuenzenmeyer This definitely does the recursion, but I also managed to get myself into an infinite loop while experimenting with this. Going to keep investigating.

**Comment by bmuenzenmeyer** [comment] 2016-02-25 20:06
Uh-oh. Lemme know whatcha did if you reproduce, else I can poke at it more too

**Comment by e2tha-e** [comment] 2016-02-26 12:06
@bmuenzenmeyer I looked at this more, and it's not an infinite loop. It's just a very long loop. What I'd been doing in Pattern Lab PHP is wrapping partial includes in conditional Mustache like
```
{{# include_foo }}
  {{> organisms-foo }}
{{/ include_foo }}
{{# include_bar }}
  {{> organisms-bar }}
{{/ include_bar }}
```

So a parameter submission like `{{> templates-includer(include_foo: true) }}` would only include `organisms-foo` and so forth. This is especially useful in Drupal-targeted projects because it would match Drupal's recursive template inclusion.

And to match a typical (big and complex) Drupal project, I'd do this _a lot_. However, since the recursion step you added to parameter_hunter.js doesn't check for the wrapping conditionals, it just recurses through every parameterized partial, which gets expensive exponentially.

I had actually hacked Pattern Lab Node's core in an earlier release to do the recursion with conditional checks, and it worked perfectly for the described scenario. However, I didn't have the time then to contribute back, and now, the core code has diverged to the point that I can't just drop in what I did and get it to work. If you don't mind, I'll keep plugging away at this until we get this feature to work in a performant manner.

**Comment by bmuenzenmeyer** [comment] 2016-02-26 13:28
I understand. Thanks for the thorough explanation. We can keep this branch as is til you have time to get to it. If you find your time slipping away, let me know - otherwise, I'm excited for the performance improvement - hopefully the currently state can serve as a foundation to build from.

**Comment by vebersol** [comment] 2016-03-02 21:13
Hi @bmuenzenmeyer @e2tha-e,

We are testing these improvements and currently the generation time for us is more 2 minutes and 50 seconds. In PHP the same amount of patterns takes 13 seconds. We have around 300 patterns.

I'm trying to figure out why the generation time is so different in both platforms.

It seems that PHP caches the generated patterns while the node version doesn't. Is that true or it might be an issue with recursion?

Thanks,
Vinícius Ebersol

**Comment by e2tha-e** [comment] 2016-03-02 21:32
@vebersol If you are testing on the 250 branch, you're likely to get unreasonably long generation times with so many patterns. I have submitted a pr for a more streamlined approach, #277 . You're welcome to test out that code. Please do provide feedback on the generation time for that, as well any errors that may arise. As of right now, I think I've got the best possible code submission given my capacity to test, and don't expect to update the pr anytime soon, unless it's in response to feedback.

**Comment by vebersol** [comment] 2016-03-02 21:35
Hi @e2tha-e,

It took more or less 40 seconds, but we've got a lot syntax erros and the result isn't the same we have in 250 branch. Are you changes from 250 in that PR?

**Comment by e2tha-e** [comment] 2016-03-02 21:50
@vebersol 40 seconds is still too long. The recursion that occurs in the 250 branch is replicated in the #277 pr. A big difference is the fact that 250 uses an eval() statement to convert the params into js objects. 277 crawls through the param strings, and iteratively parses what the object keys and values should be. This might require that you code your param strings more carefully in regard to how things are quoted, and what sort of special characters are within the param strings. On the same token, we can always manually improve the parsing algorithm. I would hate to have to revert to using the eval() statement.

The syntax errors I've encountered while testing my pr were due to param parsing errors. They will definitely lead to wrong final markup. They might also lead to longer generation times, but the more likely culprit for long generation times is extraneous recursion. Do you use conditional statements or other techniques to selectively include partials?

**Comment by vebersol** [comment] 2016-03-03 13:06
@e2tha-e yes I do. We do it in a global frontend library and we use a feature toggle in templates to show the feature we want in the pages.

**Comment by e2tha-e** [comment] 2016-03-03 15:17
@vebersol
cc @bmuenzenmeyer 
Please take a look at pr #277 at its latest commit ( 25cb4eef ). I tested this on the source/_patterns directory from an enterprise Pattern Lab PHP implementation with 268 patterns. The PHP version took about 5.5 seconds to generate. The Node version at this commit takes roughly the same amount of time. Gulp adds about .5 seconds of additional time for overhead and additional tasks for a total of around 6 seconds.

On a fresh Pattern Lab install, the PHP version takes about .3 seconds. A fresh Node implementation takes about .6 seconds not including the time added by Gulp or Grunt. At least the .3 sec difference doesn't scale.

Please test this out yourself and let me know of any issues or problems. I didn't get any syntax errors while testing out the unmodified source/_patterns directory straight from Pattern Lab PHP.

I did this on a 2012 MacBook Pro with 2.9 GHz Intel Core i7, 16GB RAM, and 750GB 5400rpm HDD.

**Comment by bmuenzenmeyer** [comment] 2016-03-03 17:30
Exciting! Thanks so much for putting more thought into optimizing this. Will check it out soon.
Makes me wonder if I should setup a "load testing environment" of sorts to monitor performance at the pattern-scales you guys are working with. Any algorithms' performance is negligible with just the shipped pattern set.

**Comment by vebersol** [comment] 2016-03-03 20:17
Hi @e2tha-e @bmuenzenmeyer 

We've made the test of your #277 and it took 26 seconds to render, while the php version takes 13 seconds.

Detected issue: the PHP version is faster after that, when you change a single file it takes less than 13 seconds and the node version takes always the same time to generate the HTML pages.

I've seen on issue using #277 and #250: when you have an organism in a template it doesn't get the variables defined in JSON. Do you know if this issue is related to #250 or #277? The dev branch isn't working correctly to compare.

**Comment by e2tha-e** [comment] 2016-03-03 20:38
@vebersol Thanks for the feedback! 26 < 40 < 170, so progress is being made! So are you still getting syntax errors? And regarding what looks like caching in the PHP version, how long does it take in those subsequent generations where only one file is changed? Also, could you describe what you mean by "organism in a template" a little more clearly?

**Comment by vebersol** [comment] 2016-03-08 12:31
Hi @e2tha-e,

Sorry about the delay.

Yes, still getting syntax errors in this branch.

The subsequent generation takes about 10% of initial generation time (in watch mode).

About the organism/molecules issues: let's suppose I have the following "molecule" (shorter than organism) and I want to get a value from template json:

**molecules/text/headline.mustache**
`
{{#showTitle}}
<header><h1>{{title}}</h1></header>
{{/showTitle}}
`

**templates/homepage.mustache**
`{{> atoms-headline }}`

**templates/homepage.json**
`{
  "showTitle": true,
  "title": "Lorem Ipsum"
}`

The expected behavior is that my molecule should get the json data, but it isn't getting the data. I hope I was clear enough.

How to reproduce: If you render the default source, the homepage emergency wouldn't show the error message.

**Comment by e2tha-e** [comment] 2016-03-08 15:32
@vebersol Thanks for the feedback. I'll look into this as soon as I can. Also, I've been working on improving this pr behind the scenes. Hopefully most of your issues will have been resolved without my being aware of them.

**Comment by e2tha-e** [comment] 2016-03-16 11:25
@vebersol 
cc @bmuenzenmeyer 
The latest commit to pr #277 can be checked out for testing: baa0f83

I think most of the discussion on error-fixing, accuracy, and performance have been in this thread so I'll continue to discuss them here, instead of in the actual pull request.

Without a doubt, at this commit, there will be a deluge of merge conflicts, which I hope to grind through reasonably soon. However, please do checkout that commit whenever you are able, and please do provide more feedback.

I think I've fixed the recursive Mustache rendering issue you described. I've kept the processing time, without Gulp tasks, to about the same as before, for the large, enterprise Pattern Lab instance. Additional Gulp tasks bring the total execution time to around 7 seconds. Oddly enough, my optimizations decreased the processing time for a fresh Pattern Lab install to a little over .4 seconds, which rivals the PHP version, albeit still slower. The entire Gulp run in both instances is 20-30% slower than PHP, and that figure scaled up, at least in my case.

Memory usage using the Mustache compiler got to nearly 1GB. This figure came from eyeballing a running Top instance, so nothing too scientific here. I switched out Mustache with Hogan, and memory usage roughly halved, to close to 500MB max. (Hogan did nothing to speeds things.) For comparison, Pattern Lab PHP uses a max of around 60MB for my enterprise Pattern Lab, an order of magnitude lighter. I don't think we should blame Gulp for the high memory consumption, since memory usage stayed around 100MB for most of the run, and only reached the peak when the frontend got built out. One of my optimizations was to write out each pattern to `public/patterns` as it was being processed, instead of processing them into a giant data object, and then iterating (yet another time) through that massive object, and then writing them to `public/patterns`. While that operation got distributed, the frontend is still built at the end by iterating though and parsing that massive data object. I think this can be improved.

As for PHP's further optimized builds during it's watch process, I think we can replicate that with targeted builds. I did nothing yet on this front, but I saw that lineage_hunter.js does nothing useful at the moment. If we accurately get a recursive lineage of all the patterns, we can do a limited build, targeting only the affected patterns by tracing its lineage upward, and only building those patterns.

Lastly, as food for thought, I realized that much of Pattern Lab is a hack to get Mustache to both accept parameters, and to include partials recursively. And as much as I love Mustache for its simplicity, and its near-reduction to bare-bones, pure (formal) logic, it was never intended to accept and parse parameters in its partial includes. This is something Handlebars (and most other templating languages) do out of the box. Out of pure curiosity at the moment, I would like to see how performant Handlebars (without additional hacks) is in the exact set of scenarios mentioned in this thread.

**Comment by geoffp** [comment] 2016-03-16 12:54
I'd love it if you'd check out the pattern-engines branch, npm install
handlebars, and re-run these tests.

I've also used Hogan in the past, very fast and lightweight. Handlebars has
a ton of compiling overhead, but once compiled, they're wicked fast.

**Comment by e2tha-e** [comment] 2016-03-16 13:40
@geoffp Hopefully I can get around to testing Handlebars, and maybe other templating languages, and publishing the results, so other devs can get something useful out of it.

**Comment by e2tha-e** [comment] 2016-03-18 16:33
@vebersol 
cc @bmuenzenmeyer 
I pushed some more code to pr #277 . You should check out and test the latest commit as of now d9ad874 . I really don't think you won't get any more syntax errors, assuming your parameter syntax was valid in Pattern Lab PHP. If you still do, you'll get much better exception handling since I replaced Node core's JSON with JSON5.

Still haven't gotten around to resolving merge conflicts. Assuming the parameter parsing is good, I'll tackle that next.

**Comment by e2tha-e** [comment] 2016-04-01 09:41
@vebersol If you have the chance, please check out the latest from #277 , commit 3883262 . The merge conflicts have been resolved, and params are parsed with JSON5, so you'll get meaningful messages if you still have syntax errors.

FYI, merging in the latest code from dev seems to have set back performance in my instance, with build times around 10 sec instead of 7. Any feedback would be greatly appreciated.

**Comment by vebersol** [comment] 2016-06-29 13:22
Hi @e2tha-e sorry about the delay to answer you, but it has been a long and busy time!

After a long time fighting against Patternlab PHP bugs and trying to migrate to Patternlab Node, without success, we've decided to create our own Atomic Design implementation. Way simple and faster than Patternlab. Obviusoly, Patternlab isn't the problem, but we realize we're using it for a different purpose but that one it was developed.

Basically, I did try to make it more Nodejs style (with all my limitation in this subject). After read Patternlab the code for some time, I noticed that this Node version of Patternlab is so much PHP style, with all problems and all good solutions from PHP. We've discussed here in the agency and we've defined to move forward with our own implementation of Brad Frost's concept.

Patternlab was our main inspiration to build our **Neutron** engine - from scratch. I appreciate your support and I apologize not being able to help you to fix this issue in time.

**Comment by e2tha-e** [comment] 2016-08-01 15:06
@bmuenzenmeyer @vebersol @geoffp I'm closing in on a pull request for this issue for Pattern Lab Node v2.x.x. I think I should have one submitted this week. The new performance is beating the work I did earlier this year by a large margin. While I've submitted several precursory prs, the main pr will probably be quite big. It would be difficult, if not impossible, to it apart break apart without breaking overall functionality.

**Comment by e2tha-e** [comment] 2016-08-01 15:17
Also, I haven't tested my code with another templating engine. It sounds like the Handlebars engine might be stable enough to try testing with, so I'll eventually give that a go. Given how Mustache-centric `parameter_hunter.js` is, I am a bit confused as to how Pattern Lab Node will work with another templating engine.

**Comment by e2tha-e** [comment] 2016-08-01 15:28
@vebersol At my last two jobs, my teams have also experienced your frustrations. There are probably hundreds of new software implementations inspired by Pattern Lab, including my own: [Fepper](https://github.com/electric-eloquence/fepper)

I've taken the fork and hack approach to solving this exact issue (#250) for Fepper. However, I'm also contributing this functionality back.

Regardless of whether we fork and hack, or start from scratch, I'm sure there an enormous amount we end up learning. I've come to appreciate so many of the decisions made by the Pattern Lab PHP team, such as opting for the Mustache language, as opposed to something obviously more powerful, like Handlebars. By working through this issue, and actually trying to solve this problem with Handlebars, I found that a feature which might appear to make Handlebars more powerful, like its strict scoping of nested parameters, actually makes it unfit for the Pattern Lab use-case.

**Comment by tommcc** [comment] 2016-10-05 14:37
Adding some examples here of cases where includes disappear due to combination of parameters or styleModifiers.

In the following scenarios, all of the buggy behavior is experienced when trying to view the organism's rendered output.

### Scenario 1 - Atom disappears entirely

**01-atoms/atom.mustache:**

```
I should appear!

```

**02-molecules/molecule.mustache:**

```
{{> atoms-atom(b: true) }}

```

**03-organisms/organism.mustache:**

```
{{> molecules-molecule(a: true) }}
```

### Scenario 2 - Atom disappears entirely

**01-atoms/atom.mustache:**

```
I should appear!

```

**02-molecules/molecule.mustache:**

```
{{> atoms-atom:x }}

```

**03-organisms/organism.mustache:**

```
{{> molecules-molecule(a: true) }}
```

**Comment by e2tha-e** [comment] 2016-10-05 15:09
@tommcc I'd encourage you check out my Pattern Lab fork: https://github.com/electric-eloquence/fepper
Most recursive parameter submission issues have been resolved there. I'll test out your example myself later, but I have a feeling that your example will render correctly.

**Comment by bmuenzenmeyer** [comment] 2016-10-05 16:37
I wonder if those two examples fail because in both, `atom.mustache` is not constructed to accept either styleModifiers or patternparameters, yet you supply them.

**Comment by tommcc** [comment] 2016-10-05 16:46
@bmuenzenmeyer: Nope—the behavior is the same while utilizing all passed-in parameters. I just took them out to make the reproduction case even simpler.

**Comment by bmuenzenmeyer** [comment] 2016-10-05 16:48
good to know, thanks

**Comment by e2tha-e** [comment] 2016-10-06 11:02
@tommcc I can confirm your example works correctly in Fepper. 😃

**Comment by tommcc** [comment] 2016-10-06 14:00
Thanks @e2tha-e for pointing Fepper. I like the features it brings, and will certainly keep an eye on it. I have heavily customized PL back- and front-ends, and for right now it makes more sense to stick with PL and hopefully help work through the small number of bugs that most affect us.

**Comment by bmuenzenmeyer** [comment] 2017-01-30 06:36
I plan to move this use case into https://github.com/pattern-lab/starterkit-mustache-acidtest to understand it's spec compliance

**Comment by JustDoItSascha** [comment] 2017-02-06 14:12
Is there any news on this issue? It's bothering me right now :(

**Comment by bmuenzenmeyer** [comment] 2017-02-06 14:15
My comment above stands. If you want to open a PR into https://github.com/pattern-lab/starterkit-mustache-acidtest using the other issue there as guidance, that would help us understand it cross-platform and have a small, reproduceable test case to build from.

**Comment by JustDoItSascha** [comment] 2017-02-06 14:54
It's exactly the test case which is part of the acidtest, I don't have to open a new PR. I'm just interesting if this issue will be fixed, because it's neraly a year old and I think it is a very important feature to create truly DRY patterns...

**Comment by bmuenzenmeyer** [comment] 2017-02-06 14:56
Team priorities are currently geared toward https://github.com/pattern-lab/patternlab-node/issues/603 with smaller 2.X things per my semi-up to date task list: https://github.com/pattern-lab/patternlab-node/projects/1

If this issue is the same as https://github.com/pattern-lab/patternlab-node/issues/539 I see no reason to have both around.

**Comment by JustDoItSascha** [comment] 2017-02-06 16:25
Too bad. It's a significant bug and I'm pretty sure it'd be easy for you to find it. Tried it myself, but the code is very complicated and without a guidance through the main parts of the code I have no chance to find the bug.

**Comment by bmuenzenmeyer** [comment] 2017-09-06 04:40
this is now working against the OP use case as of https://github.com/pattern-lab/patternlab-node/releases/tag/v2.9.3

**Closed by bmuenzenmeyer** 2017-09-06 04:40 UTC
Labels: bug, data / parsing, gap from php
