### ISSUE TITLE
Viewer - configurable size options

### ISSUE THREAD

**Issue by bennom** [pattern-lab/patternlab-node#571] opened 2016-11-30 21:02 UTC
First of all, thank you for this great project, highly appreciated!

Currently I am using Pattern Lab Node `v2.0.0` on `Mac`, with Node `v5.4.1` (I should update, hmm), using the `Gulp` Edition.

I also use the _Bootstrap v4_ for a new project that comes with an updated [grid](https://v4-alpha.getbootstrap.com/layout/grid/) splitting: `xs`, `sm`, `md`, `lg` and  `xl`. Is it possible to set the viewer options (`S`, `M`, `L` ...) to these values that the Bootstrap uses or adding a (viewport switch)? That would be great for testing and demonstrating, how the components behave based on the grid settings that the page uses. If it's not possible yet, would it make sense to make it configurable in the future? :)

**Comment by bmuenzenmeyer** [comment] 2016-11-30 21:06
Hi @bennom 

The idea behind the S, M, L is that we (designers and developers) do not have control over the viewport size of our users, so why pretend?

That said, I hope we can come up with something cross-platform for this - as many people have asked for it...

This is a duplicate of https://github.com/pattern-lab/styleguidekit-assets-default/issues/54 so I am going to consider it a :+1: for that and close.

**Closed by bmuenzenmeyer** 2016-11-30 21:06 UTC

**Comment by bennom** [comment] 2016-11-30 21:09
Hey @bmuenzenmeyer 

Didn't check that styleguidekit repo for this issue. But good know! Thank you 👍
