### ISSUE TITLE
Basic build finishes with errors (gulp edition, starterkit-mustache-demo)

### ISSUE THREAD

**Issue by softfocus** [pattern-lab/patternlab-node#837] opened 2018-04-04 19:23 UTC
Off-the-shelf starterkit-mustache-demo build finishes with errors. Any tips would appreciated!

System: Win10, Node 8.11.1, yarn 1.5.1

##### Expected Behavior

Compile working static version to public folder.

##### Actual Behavior

Build finishes but with errors. Compiled style guide navigation is broken.

###### Example error (can post all of them if necessary):

Could not find pattern referenced with partial syntax 00-atoms\00-global.md. This can occur when a pattern was renamed, moved, or no longer exists but it still referenced within a different template or within data as a link.

###### Example of malformed link:

/C:/Users/Ilja/Documents/projects/pfull/edition-node-gulp/public/patterns/00-atoms-00-global/index.html?1522868459174

##### Steps to Reproduce

1. git clone https://github.com/pattern-lab/edition-node-gulp.git
2. cd edition-node-gulp
3. yarn install
4. yarn add @pattern-lab/starterkit-mustache-demo
5. gulp patternlab:loadstarterkit --kit=@pattern-lab/starterkit-mustache-demo --clean=true
6. gulp patternlab:build

**Comment by bmuenzenmeyer** [comment] 2018-04-05 02:09
closing as duplicate of https://github.com/pattern-lab/patternlab-node/issues/786

**Closed by bmuenzenmeyer** 2018-04-05 02:09 UTC
