### ISSUE TITLE
Scroll Past Ending

### ISSUE THREAD

**Issue by adamtew** [pattern-lab/patternlab-node#198] opened 2015-12-01 21:56 UTC
Sometimes I have a pattern that will take up the whole screen, but when I open up the annotations or code panel, I can no longer see half of the pattern I was looking at. It would be nice if the page could scroll down to see the rest of the content while either panel is active. This is mostly a deal when I have multiple annotations that are lower on the page, but I can't see what is what with the annotations tab in front of the screen.

Just a thought :)

**Comment by bradfrost** [comment] 2015-12-01 22:15
Hey @AdamTew, thanks for this. This is a duplicate of [#314](https://github.com/pattern-lab/patternlab-php/issues/301) over at the PHP version. Definitely will keep it in mind for the new version!

**Comment by bmuenzenmeyer** [comment] 2015-12-03 14:31
Thanks for the pointer Brad. I occasionally get cross-over issues like this that are more frontend related. Stuff like this is a perfect reason to incorporate https://github.com/pattern-lab/styleguidekit-assets-default directly into PL Node Post 1.0.0

**Comment by bradfrost** [comment] 2015-12-03 14:39
Yeah I think that's a swell idea!

__________________________________
Brad Frost
http://bradfrost.com
http://twitter.com/brad_frost

On Thu, Dec 3, 2015 at 9:31 AM, Brian Muenzenmeyer <notifications@github.com

**Comment by bmuenzenmeyer** [comment] 2016-12-21 03:09
Duplicate https://github.com/pattern-lab/patternlab-node/issues/576

**Closed by bmuenzenmeyer** 2016-12-21 03:09 UTC
Labels: enhancement, frontend
